#!/usr/bin/env zsh
#
# Tinfoil
#
# A tool to manage multiple profiles for web browsers
#
# {{{ License
#
# Copyright (C) 2017 Dyne.org Foundation
#
# Tinfoil is designed, written and maintained by Denis Roio <jaromil@dyne.org>
#
# This source code is free software; you can redistribute it and/or
# modify it under the terms of the GNU Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This source code is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Please refer
# to the GNU Public License for more details.
#
# You should have received a copy of the GNU Public License along with
# this source code; if not, write to: Free Software Foundation, Inc.,
# 675 Mass Ave, Cambridge, MA 02139, USA.

# }}} - License

[[ "$2" = "" ]] && {
	print "usage: $0 browser profile"
	return 1
}

# read the config
eval `tinfoil conf $1 $2`
# browser="$browser"
# profile="$profile"
# profilepath="$HOME/.tinfoil/profiles/$browser.$profile"
# vendorpath="$HOME/.${vendor[$browser]}"
# cachepath="$HOME/.cache/${vendor[$browser]}"
# browser_executable="$cmd"

# generate the firejail profile
tmp=$(mktemp)
cat <<EOF >> $tmp
whitelist $vendorpath
whitelist $profilepath
whitelist $cachepath
EOF

# user configurations and installed profiles
for i in $firejail_profiles; do
	cat <<EOF >> $tmp
include $i

EOF
done

firejail --profile=$tmp tinfoil -e $browser_executable $browser $profile


# option.is_set --debug-firejail && {
#     warning "Firejail debugging mode"
#     act "CMD: firejail --profile=$ztmpfile $cmd ${=browser_opts}"
#     act "Firejail rules:"
#     cat $ztmpfile
#     act ""
#     firejail --profile=$ztmpfile $cmd ${=browser_opts}
#     return 0
# }

# option.is_set --audit-firejail && {
#     warning "Firejail audit mode"
#     act "CMD: firejail --profile=$ztmpfile --audit $cmd ${=browser_opts}"
#     firejail --profile=$ztmpfile --audit $cmd ${=browser_opts}
#     act ""
#     return 0
# }
